#!/bin/sh

iptables -F
iptables -t nat -F
iptables -X

iptables -A INPUT -i lo -j ACCEPT

iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state NEW -i eth0 -j ACCEPT
iptables -A FORWARD -i wlan0 -o eth0 -m state --state ESTABLISHED,RELATED -j ACCEPT

iptables -A FORWARD -i eth0 -o wlan0 -j ACCEPT

iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE

echo 1 > /proc/sys/net/ipv4/ip_forward

# ssh 10022 to orion
iptables -t nat -A PREROUTING -p tcp -i wlan0 --dport 10022 -j DNAT --to 192.168.2.2:22
iptables -A FORWARD -p tcp -d 192.168.2.2 --dport 10022 -j ACCEPT

# port 3000 to orion
iptables -t nat -A PREROUTING -p tcp -i wlan0 --dport 3000 -j DNAT --to 192.168.2.2:3000
iptables -A FORWARD -p tcp -d 192.168.2.2 --dport 3000 -j ACCEPT

# reject by default
iptables -A INPUT -i wlan0 -j REJECT
